const x = {
  auth_cv_result: "M",
  req_locale: "en",
  req_payer_authentication_indicator: "01",
  payer_authentication_acs_transaction_id:
    "81bcf5c4-9843-11ef-b57c-e7637db105ef",
  req_card_type_selection_indicator: "1",
  auth_trans_ref_no: "7304601368186387803047",
  payer_authentication_enroll_veres_enrolled: "Y",
  req_bill_to_surname: "Malik",
  req_card_expiry_date: "03-2028",
  req_bill_to_phone: "+966539660407",
  card_type_name: "Mastercard",
  auth_amount: "10.00",
  auth_response: "00",
  bill_trans_ref_no: "7304601368186387803047",
  req_payment_method: "card",
  req_payer_authentication_merchant_name: "ELITE CYBER TASK FORCE PV",
  auth_time: "2024-11-01T112218Z",
  transaction_id: "7304601368186387803047",
  req_card_type: "002",
  payer_authentication_transaction_id: "MRTTvvAjPa3CoAIF6a20",
  payer_authentication_pares_status: "Y",
  auth_avs_code: "U",
  auth_code: "124574",
  payer_authentication_specification_version: "2.2.0",
  req_bill_to_address_country: "SA",
  auth_cv_result_raw: "M",
  req_profile_id: "4F8E484B-08EC-42D3-B032-FED2DCF3A404",
  payer_authentication_uad: "kBNkEo8HnstomwPohWSHwhRBMow+",
  req_bill_to_address_line2: "QUARRY ROAD",
  signed_date_time: "2024-11-01T11:22:18Z",
  req_bill_to_address_line1: "ABI AL BARKAT, AL MALAZ, SAUDI ARABIA",
  payer_authentication_validate_e_commerce_indicator: "spa",
  req_card_number: "xxxxxxxxxxxx6833",
  signature: "AXo2jy8PUG9L33pvb/96gXiDKkEH2aTBIpp3UqAxOHo=",
  req_bill_to_address_city: "RIYADH",
  reason_code: "100",
  req_bill_to_forename: "TM",
  req_payer_authentication_acs_window_size: "03",
  request_token:
    "Axj//wSTi/u1Mu3F/aun/+4s3ZsGjZgxZtnDFw2ZuG7hgzYNG6fzueVOvgSfzueVOvkgK+hDShk0ky9GNWHccMKUnF/dqZduL+1dOAAA/x3a",
  req_amount: "10",
  req_bill_to_email: "thilshath@outlook.com",
  payer_authentication_reason_code: "100",
  auth_avs_code_raw: "U",
  req_currency: "LKR",
  decision: "ACCEPT",
  message: "Request was processed successfully.",
  signed_field_names:
    "auth_cv_result,req_locale,req_payer_authentication_indicator,payer_authentication_acs_transaction_id,req_card_type_selection_indicator,auth_trans_ref_no,payer_authentication_enroll_veres_enrolled,req_bill_to_surname,req_card_expiry_date,req_bill_to_phone,card_type_name,auth_amount,auth_response,bill_trans_ref_no,req_payment_method,req_payer_authentication_merchant_name,auth_time,transaction_id,req_card_type,payer_authentication_transaction_id,payer_authentication_pares_status,auth_avs_code,auth_code,payer_authentication_specification_version,req_bill_to_address_country,auth_cv_result_raw,req_profile_id,payer_authentication_uad,req_bill_to_address_line2,req_bill_to_address_line1,payer_authentication_validate_e_commerce_indicator,req_card_number,req_bill_to_address_city,reason_code,req_bill_to_forename,req_payer_authentication_acs_window_size,request_token,req_amount,req_bill_to_email,payer_authentication_reason_code,auth_avs_code_raw,req_currency,decision,message,req_transaction_uuid,payer_authentication_eci,req_transaction_type,req_access_key,req_reference_number,payer_authentication_validate_result,auth_reconciliation_reference_number,payer_authentication_uci,signed_field_names,signed_date_time",
  req_transaction_uuid: "TFNcbc4654e-e2fe-473c-85a0-9ca630e9d158",
  payer_authentication_eci: "02",
  req_transaction_type: "sale",
  req_access_key: "4aaf935e554c3078a83b5c1262c19a42",
  req_reference_number: "2024110116500036",
  payer_authentication_validate_result: "0",
  auth_reconciliation_reference_number: "430611982506",
  payer_authentication_uci: "2",
};
