const express = require("express");

// Import route files
const warrantedRoutes = require("./routes/warrantedpeople.routes");
const policeRatingRoutes = require("./routes/policeRating.routes");
const policescenereportingRoutes = require("./routes/policeSceneReporting.routes");
const policeAppointmentRoutes = require("./routes/policeAppointment.routes");
const masterPoliceRoutes = require("./routes/master-police/master-police.routes");
const dutyAllocationRoutes = require("./routes/duty-allocation/duty-allocation.routes");
const nicRoutes = require("./routes/nic/nic.routes");
const chatRoutes = require("./routes/chat/chat.routes");
const passportRoutes = require("./routes/passport/passport.routes");
const licenseRoutes = require("./routes/license/license.routes");
const stateBankRoutes = require("./routes/state-banks/stateBanks.routes");
const vehicleRoutes = require("./routes/vehicle/vehicle.routes");
const votersRoutes = require("./routes/voters-registration/votersRegistration.routes");
const electionRoutes = require("./routes/election-commission/electionCommission.routes");
const expresswayRoutes = require("./routes/expressway/expressway.routes");
const exciseRoutes = require("./routes/excise/excise.routes");
const companyRoutes = require("./routes/company/company.routes");
const cribRoutes = require("./routes/crib/crib.routes");
const ceaRoutes = require("./routes/cea/cea.routes");
const inlandRevenueRoutes = require("./routes/inland-revenue/inlandRevenue.routes");
const transportCommissionRoutes = require("./routes/transport-commission/transportCommission.routes");
const councilRoutes = require("./routes/council/council.routes");
const otherEducationalRoutes = require("./routes/other-educational-bodies/otherEducationalBodies.routes");
const gemRoutes = require("./routes/gem/gem.routes");
const epfRoutes = require("./routes/epf/epf.routes");
const etfRoutes = require("./routes/etf/etf.routes");
const universityRoutes = require("./routes/university/university.routes");
const schoolRoutes = require("./routes/school/school.routes");
const carParkServicesRoutes = require("./routes/car-park-services/carParkServices.routes");
const foreignEmploymentRoutes = require("./routes/foreign-employment-bureau/foreignEmploymentBureau.routes");
const policeWatchDogSystemNseRoutes = require("./routes/police-watchdog-system-nse/policeWatchDogSystemNse.routes");
const hospitalRoutes = require("./routes/hospital/hospital.routes");
const drivingOffenseRoutes = require("./routes/driving-offense/drivingOffense.routes");
const deviceRegistrationRoutes = require("./routes/device-registration/deviceRegistration.routes");
const mobileNetworkRoutes = require("./routes/network/network.routes");
const taxiRoutes = require("./routes/taxi/taxi.routes");
const sriLankaMedicalCouncilRoutes = require("./routes/sri-lanka-medical-council/sriLankaMedicalCouncil.routes");
const vehicleEmissionRoutes = require("./routes/vehicle-emission-certificate/vehicleEmissionCertificate.routes");
const vehicleInsuranceRoutes = require("./routes/vehicle-insurance/vehicleInsurance.routes");
const vehicleRevenueLicenseRoutes = require("./routes/vehicle-revenue-license/vehicleRevenueLicense.routes");
const atomicEnergyRoutes = require("./routes/atomic-energy-authority/atomicEnergyAuthority.routes");
const userRoutes = require("./routes/user/user.routes");
const profileRoutes = require("./routes/profile/profile.routes");
const examinationRoutes = require("./routes/examination/examination.routes");
const immigrationRoutes = require("./routes/immigration/immigration.routes");
const airlinesRoutes = require("./routes/airlines/airlines.routes");
const wesRoutes = require("./routes/search/search.routes");
const complaintRoutes = require("./routes/complaint/complaint.routes");
const customsRoutes = require("./routes/customs/customs.routes");
const userSearchRoutes = require("./routes/search/user_search.routes");
const pagesRoutes = require("./routes/pages/pages.routes");
const rightsRoutes = require("./routes/rights/rights.routes");
const citizenCodeNumberRoutes = require("./routes/citizen-code-number/citizenCodeNumber.routes");
const birthDeathMarriageRoutes = require("./routes/BirthDeathMarriage/birthDeathMarriage.routes");
const departmentChildSchoolServices = require("./routes/school/departmentSchool.routes");
const tuitionRoutes = require("./routes/tuition/tuition.routes");
const childrenTransportRoutes = require("./routes/childrenTransport/children-transport.routes");
const familyChartRoutes = require("./routes/FamilyChart/familyChart.routes");
const housemaidRoutes = require("./routes/HousemaidRoutes/Housemaid.routes");
const driverRoutes = require("./routes/DriverRoutes/Driver.Routes");
const departmentDriversOffensePortalRoutes = require("./routes/department-drivers-offense-portal/departmentDriversOffensePortal.routes");
const departmentDriversOffenseMasterRoutes = require("./routes/department-drivers-offense-master/departmentDriversOffenseMaster.routes");
const testRoutes = require("./routes/test/test.routes");
const notificationRoutes = require("./routes/notifications/notifications.routes");
const pointOfSalesRoutes = require("./routes/pointOfSales/pointOfSales.routes");
const hnbPaymentRoutes = require("./routes/hnb-payment/hnbPayment.routes");
const groupRoutes = require("./routes/group/group.routes");
const rolesRoutes = require("./routes/roles/roles.routes");
const userAffiliationsRoutes = require("./routes/user-affiliations/userAffiliations.routes");
const stockCustomerInstitutionRoutes = require("./routes/pos-stock-customer-institution/posStockCustomerInstitution.routes");
const posBillpayRoutes = require("./routes/pos-billpay/posBillpay.routes");
const posItemCaegorySubCategoryRoutes = require("./routes/pos-item-category-sub-category/posItemCategorySubCategory.routes");
const posExpensesCaegorySubCategoryRoutes = require("./routes/pos-expenses-category-sub-category/posItemCategorySubCategory.routes");
const posExpensesRoutes = require("./routes/pos-expenses/posExpensesRoutes.routes");
const pdfGenerationRoutes = require("./routes/pdf-generation/pdfGeneration.routes");
const posExpensesCashSourceRoutes = require("./routes/pos-expenses-cash-source/posExpensesCashSource.routes");
const posRepSalesVisitRoutes = require("./routes/pos-rep-sales-visit/posRepSalesVisit.routes");
const posAutoSalesSystemRoutes = require("./routes/pos-auto-sales-system/posAutoSalesSystem.routes");
const posProfitAndLossRoutes = require("./routes/pos-profit-and-loss/posProfitAndLoss.routes");
const posRepresentativesRoutes = require("./routes/pos-representatives/posRepresentatives.routes");
const stockCustomerPersonRoutes = require("./routes/pos-stock-customer-person/posStockCustomerPerson.routes");
const posTransactionsRoutes = require("./routes/pos-transactions/posTransactions.routes");
const posStockItemRoutes = require("./routes/pos-stock-item/posStockItem.routes");
const posStockRepsDispatchRoutes = require("./routes/pos-reps-stock-dispatch/posRepsStockDispatch.routes");
const posInstitutionStockActivityCheckRoutes = require("./routes/pos-institution-stock-activity-check/posInstitutionStockActivityCheck.routes");
const posBillManagementRoutes = require("./routes/pos-bill-management/posBillManagement.routes");
const posItemInformationRoutes = require("./routes/posItemInformationRoutes/posItemInformationRoutes.routes");
const posGRNDRoutes = require("./routes/pos-grn/posGRN.routes");
const posStockSupplier = require("./routes/pos-stock-supplier/posStockSupplier.routes");
const posPoDetails = require("./routes/pos-po/posPO.routes");
const cccWhitelistedRoutesRoutes = require("./routes/ccc-whitelisted-routes/cccWhitelistedRoutes.routes");
const cccAddressRoutes = require("./routes/ccc-address/cccAddress.routes");
const cccSearchRoutes = require("./routes/ccc-search/ccSearch.routes");
const cccRightsRoutes = require("./routes/ccc-rights/cccRights.controller");
const cccTrafficOffenseReportRoutes = require("./routes/ccc-traffic-offense-report/cccTrafficOffenseReport.routes");
const cccDepartmentDriversLicenseDispatchesRoutes = require("./routes/ccc-department-drivers-license-dispatches/cccDepartmentDriversLicenseDispatches.routes");
const ntbPaymentRoutes = require("./routes/payment-ntb/paymentNtb.routes");
const posRepsCommissionRoutes = require("./routes/pos-reps-commission/posRepsCommission.routes");
const cccPoliceStationRoutes = require("./routes/ccc-police-station/cccPoliceStation.routes");
const cccDepartmentDriverOffensePointsRoutes = require("./routes/ccc-department-driver-offense-points/cccDepartmentDriverOffensePoints.routes");
const cccPoliceDivisionMasterRoutes = require("./routes/ccc-police-division-master/cccPoliceDivisionMaster.routes");
const cccPoliceTrafficOfenseInsightsRoutes = require("./routes/ccc-police-traffic-offense-insights/cccPoliceTrafficOffenseInsights.routes");
const departmentDriversLicenseRevokesRoutes = require("./routes/ccc-department-driver-license-revokes/cccDepartmentDriverLicenseRevokes.routes");
const departmentSearchHistoryRoutes = require("./routes/ccc-department-search-history/cccDepartmentSearchHistory.routes");
const departmentArrestReasonsRoutes = require("./routes/ccc-department-arrest-reasons/cccDepartmentArrestReasons.routes");
const cccHotelGatewaySystemRoutes = require("./routes/ccc-hotel-gateway-system/cccHotelGatewaySystem.routes");
const cccHouseHoldersRoutes = require("./routes/house-holders/houseHolders.routes");
const countries = require("./routes/countries/countries.routes");

const router = express.Router();

// Register all routes
router.use(complaintRoutes);
router.use(warrantedRoutes);
router.use(policeRatingRoutes);
router.use(policescenereportingRoutes);
router.use(policeAppointmentRoutes);
router.use(masterPoliceRoutes);
router.use(dutyAllocationRoutes);
router.use(chatRoutes);
router.use(nicRoutes);
router.use(passportRoutes);
router.use(licenseRoutes);
router.use(stateBankRoutes);
router.use(vehicleRoutes);
router.use(votersRoutes);
router.use(electionRoutes);
router.use(expresswayRoutes);
router.use(exciseRoutes);
router.use(companyRoutes);
router.use(cribRoutes);
router.use(ceaRoutes);
router.use(inlandRevenueRoutes);
router.use(transportCommissionRoutes);
router.use(councilRoutes);
router.use(otherEducationalRoutes);
router.use(gemRoutes);
router.use(epfRoutes);
router.use(etfRoutes);
router.use(universityRoutes);
router.use(schoolRoutes);
router.use(carParkServicesRoutes);
router.use(foreignEmploymentRoutes);
router.use(policeWatchDogSystemNseRoutes);
router.use(hospitalRoutes);
router.use(drivingOffenseRoutes);
router.use(deviceRegistrationRoutes);
router.use(mobileNetworkRoutes);
router.use(taxiRoutes);
router.use(sriLankaMedicalCouncilRoutes);
router.use(vehicleEmissionRoutes);
router.use(vehicleInsuranceRoutes);
router.use(vehicleRevenueLicenseRoutes);
router.use(atomicEnergyRoutes);
router.use(userRoutes);
router.use(profileRoutes);
router.use(examinationRoutes);
router.use(immigrationRoutes);
router.use(airlinesRoutes);
router.use(wesRoutes);
router.use(customsRoutes);
router.use(pagesRoutes);
router.use(userSearchRoutes);
router.use(rightsRoutes);
router.use(citizenCodeNumberRoutes);
router.use(birthDeathMarriageRoutes);
router.use(departmentChildSchoolServices);
router.use(tuitionRoutes);
router.use(childrenTransportRoutes);
router.use(familyChartRoutes);
router.use(housemaidRoutes);
router.use(driverRoutes);
router.use(departmentDriversOffensePortalRoutes);
router.use(departmentDriversOffenseMasterRoutes);
router.use(testRoutes);
router.use(notificationRoutes);
router.use(pointOfSalesRoutes);
router.use(hnbPaymentRoutes);
router.use(groupRoutes);
router.use(rolesRoutes);
router.use(userAffiliationsRoutes);
router.use(stockCustomerInstitutionRoutes);
router.use(posBillpayRoutes);
router.use(posItemCaegorySubCategoryRoutes);
router.use(posExpensesCaegorySubCategoryRoutes);
router.use(posExpensesRoutes);
router.use(pdfGenerationRoutes);
router.use(posExpensesCashSourceRoutes);
router.use(posRepSalesVisitRoutes);
router.use(posAutoSalesSystemRoutes);
router.use(posProfitAndLossRoutes);
router.use(posRepresentativesRoutes);
router.use(stockCustomerPersonRoutes);
router.use(posTransactionsRoutes);
router.use(posStockItemRoutes);
router.use(posStockRepsDispatchRoutes);
router.use(posInstitutionStockActivityCheckRoutes);
router.use(posBillManagementRoutes);
router.use(posItemInformationRoutes); // item information
router.use(posGRNDRoutes); // pos GRN details
router.use(posStockSupplier); //pos stock supplier
router.use(posPoDetails); //pos po details
router.use(cccWhitelistedRoutesRoutes);
router.use(cccAddressRoutes);
router.use(cccSearchRoutes);
router.use(cccRightsRoutes);
router.use(cccTrafficOffenseReportRoutes);
router.use(cccDepartmentDriversLicenseDispatchesRoutes);
router.use(ntbPaymentRoutes);
router.use(posRepsCommissionRoutes);
router.use(cccPoliceStationRoutes);
router.use(cccDepartmentDriverOffensePointsRoutes);
router.use(cccPoliceDivisionMasterRoutes);
router.use(cccPoliceTrafficOfenseInsightsRoutes);
router.use(departmentDriversLicenseRevokesRoutes);
router.use(departmentSearchHistoryRoutes);
router.use(departmentArrestReasonsRoutes);
router.use(cccHotelGatewaySystemRoutes);
router.use(cccHouseHoldersRoutes);
//countries/nationalities
router.use(countries);

module.exports = router;
