import React from "react";

const CitizenCodeNumber = () => {
  return (
    <section className="mx-12 my-12">
      <div>
        Citizen Id is generated automatically for every citizen of Sri Lanka
        including all the children
        <br />
        Citizen ID number is 16 digit number
        <br />
        <br />
        1-4 is autogenerated by the system
        <br />
        <br />
        5-8 will be birth year Ex : 1989
        <br />
        <br /> Digits of 9 to 12 will be the date of birth excluding the year{" "}
        <br />
        For Example :- September 5th will be denoted as 0905
        <br />
        <br />
        13 - 16 will be birth certificate number Example : 4777
        <br />
        <br />
        The finally the number will look Like 1000 1989 0905 4777 <br />
        Where 1000 is auto generated by the system based on the search whether
        this number already exists
        <br />
      </div>
    </section>
  );
};

export default CitizenCodeNumber;
