const { DataTypes } = require("sequelize");

/**
 * Defines the DepartmentTrafficOffensePoints model, representing points associated with traffic offenses.
 * @param {Sequelize} sequelize - The Sequelize instance.
 * @returns {Model} - The DepartmentTrafficOffensePoints model.
 */
const defineDepartmentTrafficOffensePoints = (sequelize) => {
  return sequelize.define(
    "DepartmentTrafficOffensePoints",
    {
      // Primary key column with a UUID generated by default
      id: {
        type: DataTypes.UUID,
        primaryKey: true,
        defaultValue: DataTypes.UUIDV4, // Default value for UUID
        allowNull: false, // This field cannot be null
      },
      // Foreign key referencing the offense ID in DepartmentDriversOffenseMaster table
      offense_id: {
        type: DataTypes.BIGINT,
        references: {
          model: "DepartmentDriversOffenseMaster", // The associated model for this foreign key
          key: "id", // The column in the referenced model
        },
        allowNull: false, // This field cannot be null
      },
      // Points column to store points assigned for the offense, validated between 0 and 100
      points: {
        type: DataTypes.DOUBLE,
        defaultValue: 0, // Default value for points
        validate: {
          min: 0, // Minimum value for points
          max: 100, // Maximum value for points
        },
      },
      // Created by column, storing user ID from ccc_user_masterfile as a foreign key
      created_by: {
        type: DataTypes.STRING(255),
        references: {
          model: "ccc_user_masterfile", // The associated model for this foreign key
          key: "user_id", // The column in the referenced model
        },
        allowNull: true, // This field can be null, indicating no specific user may have created the record
      },
    },
    {
      // Specifies the table name
      tableName: "department_traffic_offense_points",
      // Enables automatic `created_at` and `updated_at` timestamps
      timestamps: true,
      // Enables soft deletion using `deleted_at` column
      paranoid: true,
      // Uses snake_case for automatically generated columns
      underscored: true,
    }
  );
};

module.exports = defineDepartmentTrafficOffensePoints;
