import React from 'react'
import qr  from '../assets/qr-code.png'

const myDetails = () => {
  return (
    <section>
        <div className='mx-12 my-12 bg-white text-gray-950 gap-12 p-2 flex rounded-lg justify-around'>
            <div className='flex flex-wrap justify-between gap-16'>
                <div className='border-2 rounded-lg'>
                    <img src='../img' className='w-48 h-48'/>
                </div>
                <div className=' my-4'>
                    <div className='flex gap-2'>
                        <div>
                            Name :
                        </div>
                        <div>
                            Peter Cullen
                        </div>
                    </div>
                    <div className='flex gap-2'>
                        <div>
                            Age :
                        </div>
                        <div>
                            52
                        </div>
                    </div>
                    <div className='flex gap-2'>
                        <div>
                            Address :
                        </div>
                        <div>
                            189 , Railway Road , Kollupitiya
                        </div>
                    </div>
                    <div className='flex gap-2'>
                        <div>
                            Height :
                        </div>
                        <div>
                            5'10  (177cm)
                        </div>
                    </div>
                    <div className='flex gap-2'>
                        <div>
                            Gender :
                        </div>
                        <div>
                            Male
                        </div>
                    </div>
                    <div className='flex gap-2'>
                        <div>
                            Blood Type :
                        </div>
                        <div>
                            O +
                        </div>
                    </div>
                    <div className='flex gap-2'>
                        <div>
                            Recent Criminal Record (if any) :
                        </div>
                        <div>
                            No
                        </div>
                    </div>
                </div>
                <div>
                    <img src={qr} className='w-48 h-48' />
                </div>
            </div>
        </div>
        <div className='mx-12'>
            Each citizen has a unique qr upon scanning it, they all their information [NIC , PASSPORT and driving license]  can be pulled up<br />            
            Police can scan individual qr code and perform search on roadblocks or checking whenever it is needed. Police will scan this qr code and do necessary search and find necessary information in this system.<br /><br />
            When a citizen goes to either DS Office or a hospital or a public library he will present his qr code generated by the citizen app which will contain all the above information.
       </div>
        
        <div className='mx-12 my-12 bg-white text-gray-950 gap-12 p-2 rounded-lg'>
            <h1 className='text-gray-900 font-boldmy-1 text-xl uppercase'>Verify Account</h1>

        <div className='flex flex-col gap-8'>
            <div>
                Upon Clicking should be able to open camera
            </div>
            <input type="file" accept="image/*" capture="camera" />
            <div>
                Inorder to verify the above identification. Get real time photo of the citizen and verify with the ID or license photo. <br />
                Once photo is verified , fingerprint is collected from the smartphone
            </div>
        </div>
        </div>
    </section>
  )
}

export default myDetails